# -*- coding: utf-8 -*-
"""Projeto_Gerador_de_Senha.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4qkrHBFkmAyC4lrwN9nxk4jE-t48v42
"""

#PROJETO GERADOR DE SENHA

#Maiúsculas e minúsculas
#Símbolos e espaços

#hexadecimal:
#1 = 1
#2 = 2
# até 
#9 = 9
#10 = A
#11 = B
#12 = C
#13 = D
#14 = E
#15 = F

'''
Security = chave
5ecur1ty = senha
'''

chave = input('Digite a base de sua senha: ')

senha = ''
for letra in chave:
  if letra in 'Aa':
    senha = senha + '10'
  elif letra in 'Bb':
    senha = senha + '11'
  elif letra in 'Cc':
    senha = senha + '12'
  elif letra in 'Dd':
    senha = senha + '13'
  elif letra in 'Ee':
    senha = senha + '14'
  elif letra in 'Ff':
    senha = senha + '15'
  elif letra in 'Rr':
    senha = senha + '#'
  elif letra in 'Ss':
    senha = senha + '%'
  elif letra in 'Mm':
    senha = senha + '$'
  else:
    senha = senha + letra

print(f'Esta é a sua senha criptografada: {senha}')